project:
  type: website

website:
  title: great_tables
  page-navigation: true
  navbar:
    left:
      - text: Articles
        menu:
          - articles/case-study-gtcars.qmd
      - href: reference/index.qmd
      - text: Development
        menu:
          - sidebar:examples
      - href: changelog.qmd
    right:
      - icon: github
        href: https://github.com/posit-dev/great-tables
  sidebar:
    - id: examples
      contents: examples-qmd/*

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: great_tables

  # write sidebar data to this file
  sidebar: _sidebar.yml
  dynamic: true

  sections:
    - title: Table Creation
      contents:
        - GT
    - title: Creating or modifying parts of a table
      contents:
        - GT.tab_header
        - GT.tab_spanner
        - GT.tab_stubhead
        - GT.tab_source_note
        - GT.tab_options
    - title: Formatting column data
      contents:
        - GT.fmt_number
        - GT.fmt_integer
        - GT.fmt_percent
        - GT.fmt_scientific
        - GT.fmt_currency
        - GT.fmt_bytes
        - GT.fmt_roman
        - GT.fmt_date
        - GT.fmt_time
        - GT.fmt_markdown
        - GT.fmt
    - title: Modifying columns
      contents:
        - GT.cols_align
        - GT.cols_label
        - GT.cols_move
        - GT.cols_move_to_start
        - GT.cols_move_to_end
    - title: Helper functions
      contents:
        - md
        - html
        - px
        - pct
    - title: Table options
      contents:
        - GT.opt_align_table_header
        - GT.opt_all_caps
        - GT.opt_footnote_marks
        - GT.opt_row_striping
    - title: Value formatting functions
      contents:
        - vals_fmt_number
        - vals_fmt_integer
        - vals_fmt_scientific
        - vals_fmt_percent
        - vals_fmt_currency
        - vals_fmt_roman
        - vals_fmt_bytes
        - vals_fmt_date
        - vals_fmt_time
        - vals_fmt_markdown
    - title: Built in datasets
      contents:
        - data.countrypops
        - data.sza
        - data.gtcars
        - data.sp500
        - data.pizzaplace
        - data.exibble
        - data.towny
        - data.metro
        - data.constants
        - data.illness
